services:
  dynamodb:
    image: amazon/dynamodb-local:2.5.2
    command: ["-jar", "DynamoDBLocal.jar", "-sharedDb", "-inMemory"]

  backend:
    build: ./backend
    depends_on:
      - dynamodb
    ports:
      - "4000:4000"
      - "4002:4002"
      - "4570:4570"
    environment:
      AWS_STAGE: local
      AWS_REGION: us-east-1
      DYNAMODB_ENDPOINT: http://dynamodb:8000
      S3_LOCAL_ENDPOINT: http://localhost:4570
      AWS_ACCESS_KEY_ID: local
      AWS_SECRET_ACCESS_KEY: local
    volumes:
      - ./backend:/app
      - backend_node_modules:/app/node_modules
      - backend_serverless:/app/.serverless
      - backend_s3:/app/.s3
    command: ["npm", "run", "offline", "--", "--stage", "local", "--httpPort", "4000", "--lambdaPort", "4002", "--host", "0.0.0.0"]

  frontend:
    build: ./frontend
    depends_on:
      - backend
    ports:
      - "3000:3000"
    environment:
      VITE_API_URL: http://localhost:4000
    volumes:
      - ./frontend:/app
      - frontend_node_modules:/app/node_modules
    command: ["npm", "run", "dev", "--", "--host", "0.0.0.0"]

volumes:
  backend_node_modules:
  backend_serverless:
  backend_s3:
  frontend_node_modules:

